version: '3'
services:
  coder-fastapi-test:
    container_name: coder-fastapi-test
    image: coder-fastapi:test
    build:
      context: .
    volumes:
      - .:/home/coder/coder-fastapi
      - /home/coder/coder-fastapi/coderfastapi.egg-info
    networks:
      - test
    env_file:
      - cache.env.test
    depends_on:
      - cache-test
    tty: true
    stdin_open: true
  cache-test:
    container_name: coder-fastapi-cache-test
    image: redis:7
    networks:
      - test
    env_file:
      - cache.env.test
networks:
  test:
